server:
  port: 9000

spring:
  application:
    name: spring-ai-alibaba-dashscope-chat
  ai:
    dashscope:
      api-key: ${DASHSCOPE_API_KEY}

# enabled debug log out.
#logging:
#  level:
#    org.springframework.ai: debug
#    com.alibaba.dashscope.api: debug
#    com.alibaba.cloud.ai.dashscope.chat: debug