server:
  port: 10000

spring:
  application:
    name: spring-ai-alibaba-dashscope-chat
  ai:
    dashscope:
      api-key: sk-5fe2997e181e432297756487354b3798

# enabled debug log out.
logging:
  level:
    org.springframework.ai: debug
    com.alibaba.dashscope.api: debug
    com.alibaba.cloud.ai.dashscope.chat: debug