server:
  port: 10003

spring:
  application:
    name: spring-ai-alibaba-openai-chat
  ai:
    openai:
      api-key: ${DASHSCOPE_API_KEY}

# enabled debug log out.
logging:
  level:
    org.springframework.ai: debug
    com.alibaba.dashscope.api: debug
    com.alibaba.cloud.ai.dashscope.chat: debug